<div class="footer">
	<footer>
		<h3 class="Footer-Ack">Acknowledgement of Country</h3>
		<p>
			At FakeShop, we respectfully acknowledge the Wurundjeri People of the
			Kulin Nation, who are the Traditional Owners of the land on which
			FakeShop's HQ is located in Melbourne’s east and pay our respect to their
			Elders past, present and emerging. We are honoured to recognise our
			connection to Wurundjeri Country, history, culture and spirituality
			through these locations, and strive to ensure that we operate in a manner
			that respects and honours the Elders and Ancestors of these lands. We also
			acknowledge and respect the Traditional Owners of lands across Australia,
			their Elders, Ancestors, cultures and heritage, and recognise the
			continuing sovereignties of all Aboriginal and Torres Strait Islander
			Nations.
		</p>
		<img
			src="images/indigenous-acknowledgement.svg"
			alt="Acknowledgement Flags" />
		<!--quick footer so we don't forget. Can be changed. Put this in a div box-->
		<a href="https://www.swinburne.edu.au/"
			>| &copy;Swinburne University of Technology |
		</a>
		<a href="./index.php">&copy;FakeShop</a>
		<a
			href="https://wtp-group5-wed-230.atlassian.net?continue=https%3A%2F%2Fwtp-group5-wed-230.atlassian.net%2Fwelcome%2Fsoftware&atlOrigin=eyJpIjoiNDI3YzZkN2EyZjc2NDQ0MzlkNGY2MWRkNzIzZGU1MWYiLCJwIjoiaiJ9"
			>Jira Board |
		</a>
		<a href="https://github.com/Reave2323/WebTechProjectGroup5"
			>Github Repository |
		</a>
		<a href="https://reave2323.github.io/WebTechProjectGroup5/">Live Site | </a>
		<a href="mailto:info@fakeshop.com">Need to Contact Us?</a>
	</footer>
</div>
